create table if not exists cart_items (
    id bigint generated by default as identity primary key,
    visitor_id text not null,
    ip_address inet,
    product_name text not null,
    category text,
    price text,
    image_url text,
    quantity integer not null default 1 check (quantity > 0),
    discount_code text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (visitor_id, ip_address, product_name)
);

create or replace function set_cart_items_updated_at()
returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

drop trigger if exists set_cart_items_updated_at on cart_items;

create trigger set_cart_items_updated_at
before update on cart_items
for each row
execute function set_cart_items_updated_at();

alter table cart_items enable row level security;

drop policy if exists "cart items are public readable" on cart_items;
drop policy if exists "cart items are public insertable" on cart_items;
drop policy if exists "cart items are public updatable" on cart_items;
drop policy if exists "cart items are public deletable" on cart_items;

create policy "cart items are public readable"
on cart_items
for select
using (true);

create policy "cart items are public insertable"
on cart_items
for insert
with check (true);

create policy "cart items are public updatable"
on cart_items
for update
using (true)
with check (true);

create policy "cart items are public deletable"
on cart_items
for delete
using (true);
