create table if not exists products (
    id bigint generated by default as identity primary key,
    name text not null,
    category text not null check (category in ('waschbecken', 'wc', 'dusche')),
    description text,
    price text,
    article_number text,
    image_url text,
    material text,
    active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamptz not null default now()
);

alter table products enable row level security;

create policy "products are public readable"
on products
for select
using (active = true);

insert into products (name, category, description, price, article_number, image_url, material, sort_order)
values
('Geberit ONE Moebelwaschtisch', 'waschbecken', 'Moderner Waschtisch fuer klare Badezimmergestaltung.', '383,28 EUR', null, 'https://www.obadis.com/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/k/a/kataloge_geberit_vgabild_geb_w_2226616_20210914_112611.jpeg___/Geberit-One-Moebel-Waschtisch-505002001-60-cm,-Hahnloch-mittig,-ohne-Ueberlauf,-weiss-KeraTect-Blende-weiss.jpeg', 'Sanitaerkeramik KeraTect', 10),
('Geberit iCon Light Waschtisch', 'waschbecken', 'Hochwertiger Waschtisch mit zeitloser Form.', '369,54 EUR', null, 'https://www.obadis.com/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/k/a/kataloge_geberit_vgabild_geb_w_1889931_20200923_165731.jpeg___/Geberit-iCon-light-Waschtisch-501837001-120x48cm,-Hahnloch-links-rechts,-mit-Ueberlauf,-weiss.jpeg', 'Feuerton Spezialglasur', 20),
('Geberit AquaClean Mera', 'wc', 'Hochwertige Dusch-WC-Loesung mit komfortabler Technik.', 'ab 3660 EUR', 'ART-146210111', 'https://www.baedermaxx.at/media/image/b4/1f/60/Geberit-AquaClean-Mera-Comfort-Wand-Dusch-WC-Komplettanlage_600x600@2x.webp', 'Sanitaerkeramik', 30),
('Geberit iCon Wand-WC Rimfree', 'wc', 'Spuelrandloses Wand-WC mit moderner Optik.', '372,15 EUR', null, 'https://www.obadis.com/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/k/a/kataloge_geberit_milieu_gemi_cs1038062228.jpeg___/Geberit-iCon-WC-Set-Wand-Tiefspuel-WC-501664008-36x53cm,--geschlossene-Form,-rimfree,-mit-WC-Sitz,-weiss-KeraTect.jpeg', 'Spuelrandlose Keramik', 40),
('Geberit CleanLine Edelstahl-Duschrinne', 'dusche', 'Bodenebene Duschrinne mit sauberer Edelstahloptik.', '363,32 EUR', null, 'https://www.obadis.com/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/k/a/kataloge_geberit_milieu_gemi_cs29337358.jpeg___/Geberit-CleanLine-50-Duschrinne-154448KS2-30-110-x-3-cm,-Edelstahl-gebuerstet,-bodeneben.jpeg', 'Edelstahl matt / poliert', 50),
('Geberit Olona Design-Duschflaeche', 'dusche', 'Flache Duschflaeche fuer moderne Badezimmer.', '631,59 EUR', null, 'https://www.obadis.com/media/catalog/product/cache/207e23213cf636ccdef205098cf3c8a3/k/a/kataloge_geberit_vgabild_geb_w_4077617_20240426_065545.jpeg___/Geberit-Olona-Rechteckduschwanne-550919001-weiss-matt,-140-x-90-x-4-cm.jpeg', 'Stein-Harz-Mineralwerkstoff', 60);
