create table if not exists product_clicks (
    id bigint generated by default as identity primary key,
    visitor_id text not null,
    ip_address inet,
    product_name text not null,
    category text,
    page_path text,
    user_agent text,
    created_at timestamptz not null default now()
);

alter table product_clicks add column if not exists ip_address inet;

alter table product_clicks enable row level security;

drop policy if exists "product clicks are public insertable" on product_clicks;

create policy "product clicks are public insertable"
on product_clicks
for insert
with check (true);
